/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "s21_math_test.check" instead.
 */

#include "s21_math.h"

#include <check.h>
#include <limits.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

#define LEN 256

START_TEST(s21_sin_circle) {
  double testcases[] = {0,
                        S21_PI / 6,
                        S21_PI / 4,
                        S21_PI / 3,
                        S21_PI / 2,
                        2 * S21_PI / 3,
                        3 * S21_PI / 4,
                        5 * S21_PI / 6,
                        S21_PI,
                        7 * S21_PI / 6,
                        5 * S21_PI / 4,
                        4 * S21_PI / 3,
                        3 * S21_PI / 2,
                        -S21_PI / 3,
                        -S21_PI / 4,
                        -S21_PI / 6,
                        2 * S21_PI};

  size_t n = sizeof(testcases) / sizeof(testcases[0]);

  for (size_t i = 0; i < n; i++) {
    long double result = s21_sin(testcases[i]);
    double expected = sin(testcases[i]);
    ck_assert_ldouble_eq_tol(expected, result, 0.000001);
  }
}
END_TEST

START_TEST(s21_sin_random) {
  srand(time(NULL));

  size_t n = 10;
  double lowerBorder = -10 * S21_PI;
  double upperBorder = 10 * S21_PI;

  for (size_t i = 0; i < n; i++) {
    double arg =
        lowerBorder + (rand() / (double)RAND_MAX) * (upperBorder - lowerBorder);
    long double result = s21_sin(arg);
    double expected = sin(arg);
    ck_assert_ldouble_eq_tol(expected, result, 0.000001);
  }
}
END_TEST

START_TEST(s21_sin_extreme) {
  long double result = s21_sin(NAN);
  ck_assert_ldouble_nan(result);

  result = s21_sin(+INFINITY);
  ck_assert_ldouble_nan(result);

  result = s21_sin(-INFINITY);
  ck_assert_ldouble_nan(result);
}
END_TEST

START_TEST(s21_cos_circle) {
  double testcases[] = {0,
                        S21_PI / 6,
                        S21_PI / 4,
                        S21_PI / 3,
                        S21_PI / 2,
                        2 * S21_PI / 3,
                        3 * S21_PI / 4,
                        5 * S21_PI / 6,
                        S21_PI,
                        7 * S21_PI / 6,
                        5 * S21_PI / 4,
                        4 * S21_PI / 3,
                        3 * S21_PI / 2,
                        -S21_PI / 3,
                        -S21_PI / 4,
                        -S21_PI / 6,
                        2 * S21_PI};

  size_t n = sizeof(testcases) / sizeof(testcases[0]);

  for (size_t i = 0; i < n; i++) {
    long double result = s21_cos(testcases[i]);
    double expected = cos(testcases[i]);
    ck_assert_ldouble_eq_tol(expected, result, 0.000001);
  }
}
END_TEST

START_TEST(s21_cos_random) {
  srand(time(NULL));

  size_t n = 10;
  double lowerBorder = -10 * S21_PI;
  double upperBorder = 10 * S21_PI;

  for (size_t i = 0; i < n; i++) {
    double arg =
        lowerBorder + (rand() / (double)RAND_MAX) * (upperBorder - lowerBorder);
    long double result = s21_cos(arg);
    double expected = cos(arg);
    ck_assert_ldouble_eq_tol(expected, result, 0.000001);
  }
}
END_TEST

START_TEST(s21_cos_extreme) {
  long double result = s21_cos(NAN);
  ck_assert_ldouble_nan(result);

  result = s21_cos(+INFINITY);
  ck_assert_ldouble_nan(result);

  result = s21_cos(-INFINITY);
  ck_assert_ldouble_nan(result);
}
END_TEST

START_TEST(s21_tan_circle) {
  double testcases[] = {0,
                        S21_PI / 6,
                        S21_PI / 4,
                        S21_PI / 3,
                        2 * S21_PI / 3,
                        3 * S21_PI / 4,
                        5 * S21_PI / 6,
                        S21_PI,
                        7 * S21_PI / 6,
                        5 * S21_PI / 4,
                        4 * S21_PI / 3,
                        -S21_PI / 3,
                        -S21_PI / 4,
                        -S21_PI / 6,
                        2 * S21_PI};

  size_t n = sizeof(testcases) / sizeof(testcases[0]);

  for (size_t i = 0; i < n; i++) {
    long double result = s21_tan(testcases[i]);
    double expected = tan(testcases[i]);
    ck_assert_ldouble_eq_tol(expected, result, 0.000001);
  }
}
END_TEST

START_TEST(s21_tan_random) {
  srand(time(NULL));

  size_t n = 10;
  double lowerBorder = -S21_PI / 2.01;
  double upperBorder = S21_PI / 2.01;

  for (size_t i = 0; i < n; i++) {
    double arg =
        lowerBorder + (rand() / (double)RAND_MAX) * (upperBorder - lowerBorder);
    if (rand() % 2) {
      arg += S21_PI;
    }
    long double result = s21_tan(arg);
    double expected = tan(arg);
    ck_assert_ldouble_eq_tol(expected, result, 0.000001);
  }
}
END_TEST

START_TEST(s21_tan_extreme) {
  long double result = s21_tan(NAN);
  ck_assert_ldouble_nan(result);

  result = s21_tan(+INFINITY);
  ck_assert_ldouble_nan(result);

  result = s21_tan(-INFINITY);
  ck_assert_ldouble_nan(result);

  result = s21_tan(S21_PI / 2);
  ck_assert_ldouble_infinite(result);

  result = s21_tan(-S21_PI / 2);
  ck_assert_ldouble_infinite(result);

  result = s21_tan(5 * S21_PI / 2);
  ck_assert_ldouble_infinite(result);
}
END_TEST

START_TEST(s21_acos_circle) {
  double testcases[] = {1,        sqrt(3.) / 2, sqrt(2.) / 2,  1. / 2.,
                        0,        -1. / 2.,     -sqrt(2.) / 2, -sqrt(3.) / 2,
                        -1,       0.9999,       0.99999,       -0.999999,
                        0.999995, -0.000001,    0.000005,      -0.00000008,
                        0.9999995};

  size_t n = sizeof(testcases) / sizeof(testcases[0]);

  for (size_t i = 0; i < n; i++) {
    long double result = s21_acos(testcases[i]);
    double expected = acos(testcases[i]);
    ck_assert_ldouble_eq_tol(expected, result, 0.000001);
  }
}
END_TEST

START_TEST(s21_acos_random) {
  srand(time(NULL));

  size_t n = 10;
  double lowerBorder = -1;
  double upperBorder = 1;

  for (size_t i = 0; i < n; i++) {
    double arg =
        lowerBorder + (rand() / (double)RAND_MAX) * (upperBorder - lowerBorder);
    long double result = s21_acos(arg);
    double expected = acos(arg);
    ck_assert_ldouble_eq_tol(expected, result, 0.000001);
  }
}
END_TEST

START_TEST(s21_acos_extreme) {
  long double result = s21_acos(NAN);
  ck_assert_ldouble_nan(result);

  result = s21_acos(+INFINITY);
  ck_assert_ldouble_nan(result);

  result = s21_acos(-INFINITY);
  ck_assert_ldouble_nan(result);

  result = s21_acos(-8);
  ck_assert_ldouble_nan(result);

  result = s21_acos(1.0000000001);
  ck_assert_ldouble_nan(result);
}
END_TEST

START_TEST(s21_asin_circle) {
  double testcases[] = {-1,       -sqrt(3.) / 2, -sqrt(2.) / 2, -1. / 2.,
                        0,        1. / 2.,       sqrt(2.) / 2,  sqrt(3.) / 2,
                        1,        0.9999,        0.99999,       -0.999999,
                        0.999995, -0.000001,     0.000005,      -0.00000008,
                        0.9999995};

  size_t n = sizeof(testcases) / sizeof(testcases[0]);

  for (size_t i = 0; i < n; i++) {
    long double result = s21_asin(testcases[i]);
    double expected = asin(testcases[i]);
    ck_assert_ldouble_eq_tol(expected, result, 0.000001);
  }
}
END_TEST

START_TEST(s21_asin_random) {
  srand(time(NULL));

  size_t n = 10;
  double lowerBorder = -1;
  double upperBorder = 1;

  for (size_t i = 0; i < n; i++) {
    double arg =
        lowerBorder + (rand() / (double)RAND_MAX) * (upperBorder - lowerBorder);
    long double result = s21_asin(arg);
    double expected = asin(arg);
    ck_assert_ldouble_eq_tol(expected, result, 0.000001);
  }
}
END_TEST

START_TEST(s21_asin_extreme) {
  long double result = s21_asin(NAN);
  ck_assert_ldouble_nan(result);

  result = s21_asin(+INFINITY);
  ck_assert_ldouble_nan(result);

  result = s21_asin(-INFINITY);
  ck_assert_ldouble_nan(result);

  result = s21_asin(-8);
  ck_assert_ldouble_nan(result);

  result = s21_asin(1.0000000001);
  ck_assert_ldouble_nan(result);
}
END_TEST

START_TEST(s21_atan_circle) {
  double testcases[] = {-sqrt(3.),    -1, -sqrt(3.) / 3, 0,
                        sqrt(3.) / 3, 1,  sqrt(3.)};

  size_t n = sizeof(testcases) / sizeof(testcases[0]);

  for (size_t i = 0; i < n; i++) {
    long double result = s21_atan(testcases[i]);
    double expected = atan(testcases[i]);
    ck_assert_ldouble_eq_tol(expected, result, 0.000001);
  }
}
END_TEST

START_TEST(s21_atan_random) {
  srand(time(NULL));

  size_t n = 10;

  double lowerBorder = 0;
  double upperBorder = 0;

  int category = rand() % 100;
  if (category < 95) {
    lowerBorder = -10;
    upperBorder = 10;
  } else if (category < 99) {
    lowerBorder = -1000;
    upperBorder = 1000;
  } else {
    lowerBorder = -1e100;
    upperBorder = 1e100;
  }

  for (size_t i = 0; i < n; i++) {
    double arg =
        lowerBorder + (rand() / (double)RAND_MAX) * (upperBorder - lowerBorder);
    long double result = s21_atan(arg);
    double expected = atan(arg);
    ck_assert_ldouble_eq_tol(expected, result, 0.000001);
  }
}
END_TEST

START_TEST(s21_atan_extreme) {
  long double result = s21_atan(NAN);
  ck_assert_ldouble_nan(result);

  result = s21_atan(+INFINITY);
  ck_assert_ldouble_eq_tol(S21_PI / 2, result, 0.000001);

  result = s21_atan(-INFINITY);
  ck_assert_ldouble_eq_tol(-S21_PI / 2, result, 0.000001);
}
END_TEST

START_TEST(s21_fmod_common) {
  struct test_data {
    double x;
    double y;
  };

  struct test_data testcases[] = {{1., 1.},
                                  {42., 21.},
                                  {21., 42.},
                                  {10., 9.},
                                  {8., 3.},
                                  {14., 6.},
                                  {2.5, 0.3},
                                  {1., 0.3333333333},
                                  {9.9, 3.3},
                                  {99999.99999, 0.00001},
                                  {123.456, 78.91011},
                                  {-5., 3.},
                                  {-6., -2.5},
                                  {-49.9, 36.6}};

  size_t n = sizeof(testcases) / sizeof(testcases[0]);

  for (size_t i = 0; i < n; i++) {
    double expected = fmod(testcases[i].x, testcases[i].y);
    long double result = s21_fmod(testcases[i].x, testcases[i].y);
    ck_assert_ldouble_eq_tol(expected, result, 0.000001);
  }
}
END_TEST

START_TEST(s21_fmod_random) {
  srand(time(NULL));

  size_t n = 10;
  double lowerBorder = -42e21;
  double upperBorder = 21e42;

  for (size_t i = 0; i < n; i++) {
    double x =
        lowerBorder + (rand() / (double)RAND_MAX) * (upperBorder - lowerBorder);
    double y =
        lowerBorder + (rand() / (double)RAND_MAX) * (upperBorder - lowerBorder);
    long double result = s21_fmod(x, y);
    double expected = fmod(x, y);
    ck_assert_ldouble_eq_tol(expected, result, 0.000001);
  }
}
END_TEST

START_TEST(s21_fmod_extreme) {
  long double result = s21_fmod(1., 0.);
  ck_assert_ldouble_nan(result);

  result = s21_fmod(21., INFINITY);
  ck_assert_ldouble_eq_tol(21., result, 0.000001);

  result = s21_fmod(42., -INFINITY);
  ck_assert_ldouble_eq_tol(42., result, 0.000001);

  result = s21_fmod(-21., -INFINITY);
  ck_assert_ldouble_eq_tol(-21., result, 0.000001);

  result = s21_fmod(-42., INFINITY);
  ck_assert_ldouble_eq_tol(-42., result, 0.000001);

  result = s21_fmod(INFINITY, INFINITY);
  ck_assert_ldouble_nan(result);

  result = s21_fmod(-INFINITY, INFINITY);
  ck_assert_ldouble_nan(result);

  result = s21_fmod(INFINITY, -INFINITY);
  ck_assert_ldouble_nan(result);

  result = s21_fmod(-INFINITY, -INFINITY);
  ck_assert_ldouble_nan(result);

  result = s21_fmod(NAN, 42.);
  ck_assert_ldouble_nan(result);

  result = s21_fmod(21., NAN);
  ck_assert_ldouble_nan(result);

  result = s21_fmod(NAN, NAN);
  ck_assert_ldouble_nan(result);
}
END_TEST

START_TEST(s21_sqrt_rational) {
  double testcases[] = {0.,
                        1.,
                        4.,
                        9.,
                        16.,
                        25.,
                        44.,
                        128.,
                        99.,
                        1002345.,
                        123.456812313e20,
                        0.00000000000004,
                        64e-12};

  size_t n = sizeof(testcases) / sizeof(testcases[0]);

  for (size_t i = 0; i < n; i++) {
    long double result = s21_sqrt(testcases[i]);
    double expected = sqrt(testcases[i]);
    char result_str[LEN];
    char expected_str[LEN];
    sprintf(result_str, "%16.6Lf", result);
    sprintf(expected_str, "%16.6lf", expected);
    ck_assert_ldouble_eq_tol(result, expected, 0.000001);
    // ck_assert_pstr_eq(result_str, expected_str);
  }
}
END_TEST

START_TEST(s21_sqrt_irrational) {
  double testcases[] = {2.,
                        3.,
                        5.,
                        7.,
                        11.,
                        13.,
                        17.,
                        799015403.,
                        945804449.,
                        51795199.,
                        834477235658681.,
                        92751910095643.,
                        1716204879506222369317.};

  size_t n = sizeof(testcases) / sizeof(testcases[0]);

  for (size_t i = 0; i < n; i++) {
    long double result = s21_sqrt(testcases[i]);
    double expected = sqrt(testcases[i]);
    char result_str[LEN];
    char expected_str[LEN];
    sprintf(result_str, "%16.6Lf", result);
    sprintf(expected_str, "%16.6lf", expected);
    ck_assert_ldouble_eq_tol(result, expected, 0.000001);
    // ck_assert_pstr_eq(result_str, expected_str);
  }
}
END_TEST

START_TEST(s21_sqrt_random) {
  srand(time(NULL));

  size_t n = 10;
  double lowerBorder = 0.;
  double upperBorder = 1e20;

  for (size_t i = 0; i < n; i++) {
    double arg =
        lowerBorder + (rand() / (double)RAND_MAX) * (upperBorder - lowerBorder);
    long double result = s21_sqrt(arg);
    double expected = sqrt(arg);
    char result_str[LEN];
    char expected_str[LEN];
    sprintf(result_str, "%16.6Lf", result);
    sprintf(expected_str, "%16.6lf", expected);
    ck_assert_ldouble_eq_tol(result, expected, 0.000001);
    // ck_assert_pstr_eq(result_str, expected_str);
  }
}
END_TEST

START_TEST(s21_sqrt_extreme) {
  long double result = s21_sqrt(-8.);
  ck_assert_ldouble_nan(result);

  result = s21_sqrt(INFINITY);
  ck_assert_ldouble_infinite(result);

  result = s21_sqrt(-INFINITY);
  ck_assert_ldouble_nan(result);

  result = s21_sqrt(NAN);
  ck_assert_ldouble_nan(result);
}
END_TEST

START_TEST(s21_ceil_regular) {
  double testcases[] = {0,
                        0.000001,
                        -0.000001,
                        1.000001,
                        -1.000001,
                        0.999999,
                        -0.999999,
                        1.999999,
                        -1.999999,
                        1,
                        -1,
                        1.000001,
                        -1.000001,
                        1.5,
                        -1.5,
                        INT_MAX,
                        INT_MIN,
                        LLONG_MIN,
                        LLONG_MAX,
                        123456789.123456,
                        123456789.123456,
                        481516.2342,
                        -481516.2342,
                        .0000045,
                        -.0000045,
                        +.0000045};
  size_t n = sizeof(testcases) / sizeof(testcases[0]);

  for (size_t i = 0; i < n; i++) {
    long double result = s21_ceil(testcases[i]);
    double expected_result = ceil(testcases[i]);
    ck_assert_ldouble_eq_tol(result, expected_result, 0.000001);
  }
}
END_TEST

START_TEST(s21__ceil_infnan) {
  long double result = s21_ceil(NAN);
  ck_assert_ldouble_nan(result);

  result = s21_ceil(INFINITY);
  ck_assert_ldouble_infinite(result);

  result = s21_ceil(-INFINITY);
  ck_assert_ldouble_infinite(result);
}
END_TEST

START_TEST(s21_floor_regular) {
  double testcases[] = {0,
                        0.000001,
                        -0.000001,
                        1.000001,
                        -1.000001,
                        0.999999,
                        -0.999999,
                        1.999999,
                        -1.999999,
                        1,
                        -1,
                        1.000001,
                        -1.000001,
                        1.5,
                        -1.5,
                        INT_MAX,
                        INT_MIN,
                        LLONG_MIN,
                        LLONG_MAX,
                        123456789.123456,
                        123456789.123456,
                        481516.2342,
                        -481516.2342,
                        .0000045,
                        -.0000045,
                        +.0000045};
  size_t n = sizeof(testcases) / sizeof(testcases[0]);

  for (size_t i = 0; i < n; i++) {
    long double result = s21_floor(testcases[i]);
    double expected_result = floor(testcases[i]);
    ck_assert_ldouble_eq_tol(result, expected_result, 0.000001);
  }
}
END_TEST

START_TEST(s21_floor_infnan) {
  long double result = s21_floor(NAN);
  ck_assert_ldouble_nan(result);

  result = s21_floor(INFINITY);
  ck_assert_ldouble_infinite(result);

  result = s21_floor(-INFINITY);
  ck_assert_ldouble_infinite(result);
}
END_TEST

START_TEST(s21_exp_regular) {
  double testcases[] = {
      0,        0.000001,  -0.000001, 1.000001,  -1.000001, 0.999999, -0.999999,
      1.999999, -1.999999, 1,         2,         5,         10,       15,
      1.1,      1.001,     1.0001,    1.00001,   9.999999,  5.454545, 5.4444445,
      1,        -1,        1.000001,  -1.000001, 1.5,       -1.5,     INT_MIN,
      //	LLONG_MIN, 12345.123456, -123456789.123456,
      //	4816.2342, -481516.2342, .0000045, -.0000045, +.0000045
  };
  size_t n = sizeof(testcases) / sizeof(testcases[0]);

  for (size_t i = 0; i < n; i++) {
    long double result = s21_exp(testcases[i]);
    double expected_result = exp(testcases[i]);
    char result_str[LEN];
    char expected_str[LEN];
    sprintf(result_str, "%16.6Lf", result);
    sprintf(expected_str, "%16.6lf", expected_result);
    ck_assert_ldouble_eq_tol(result, expected_result, 0.000001);
    // ck_assert_pstr_eq(result_str, expected_str);
  }
}
END_TEST

START_TEST(s21_exp_infnan) {
  long double result = s21_exp(NAN);
  ck_assert_ldouble_nan(result);

  result = s21_exp(INFINITY);
  ck_assert_ldouble_infinite(result);

  result = s21_exp(-INFINITY);
  ck_assert_ldouble_eq(result, 0);
}
END_TEST

START_TEST(s21_log_regular) {
  double testcases[] = {0.000001,
                        1.000001,
                        0.999999,
                        1.999999,
                        1,
                        2,
                        5,
                        50,
                        150,
                        1.1,
                        1.001,
                        1.0001,
                        1.00001,
                        9.999999,
                        5.454545,
                        5.4444445,
                        1,
                        1.000001,
                        1.5,
                        INT_MAX,
                        LLONG_MAX,
                        123456789.123456,
                        123456789.123456,
                        481516.2342,
                        .0000045,
                        +.0000045};
  size_t n = sizeof(testcases) / sizeof(testcases[0]);

  for (size_t i = 0; i < n; i++) {
    long double result = s21_log(testcases[i]);
    double expected_result = log(testcases[i]);
    char result_str[LEN];
    char expected_str[LEN];
    sprintf(result_str, "%16.6Lf", result);
    sprintf(expected_str, "%16.6lf", expected_result);
    ck_assert_ldouble_eq_tol(result, expected_result, 0.000001);
    // ck_assert_pstr_eq(result_str, expected_str);
  }
}
END_TEST

START_TEST(s21_log_infnan) {
  long double result = s21_log(NAN);
  ck_assert_ldouble_nan(result);

  result = s21_log(INFINITY);
  ck_assert_ldouble_infinite(result);
}
END_TEST

START_TEST(s21_abs_regular) {
  int testcases[] = {0, -1000001, 999999,  +1999999, 1,
                     -2,    5,        -50,      150,     -11,      -1001,
                     10001, INT_MAX,  INT_MIN,  1234567, -1234567, -0,
                     0,     00,       +00,      -00};
  size_t n = sizeof(testcases) / sizeof(testcases[0]);

  for (size_t i = 0; i < n; i++) {
    int result = s21_abs(testcases[i]);
    int expected_result = abs(testcases[i]);
    ck_assert_int_eq(result, expected_result);
  }
}
END_TEST

START_TEST(s21_fabs_regular) {
  double testcases[] = {0,
                        0.000001,
                        -0.000001,
                        1.000001,
                        -1.000001,
                        0.999999,
                        -0.999999,
                        1.999999,
                        -1.999999,
                        1,
                        2,
                        5,
                        50,
                        150,
                        1.1,
                        1.001,
                        1.0001,
                        1.00001,
                        9.999999,
                        5.454545,
                        5.4444445,
                        1,
                        -1,
                        1.000001,
                        -1.000001,
                        1.5,
                        -1.5,
                        INT_MAX,
                        INT_MIN,
                        LLONG_MIN,
                        LLONG_MAX,
                        123456789.123456,
                        123456789.123456,
                        481516.2342,
                        -481516.2342,
                        .0000045,
                        -.0000045,
                        +.0000045};
  size_t n = sizeof(testcases) / sizeof(testcases[0]);

  for (size_t i = 0; i < n; i++) {
    long double result = s21_fabs(testcases[i]);
    double expected_result = fabs(testcases[i]);
    ck_assert_ldouble_eq_tol(result, expected_result, 0.000001);
  }
}
END_TEST

START_TEST(s21_fabs_infnan) {
  long double result = s21_fabs(NAN);
  ck_assert_ldouble_nan(result);

  result = s21_fabs(INFINITY);
  ck_assert_ldouble_infinite(result);

  result = s21_fabs(-INFINITY);
  ck_assert_ldouble_infinite(result);
}
END_TEST

START_TEST(s21_pow_regular) {
  double testcases_base[] = {0.1,   1.01,  1.001, 0.9,  0.99,  1.49,  1.59,
                             1.1,   2.5,   4.8,   5.0,  10,    4.47,  4.51,
                             5.001, 2.121, 4.242, 9.99, 7.055, 5.900, 0.5,
                             0.9,   0.8,   2.3,   21.2, 21.1,  +1.21, 1.29};
  double testcases_exp[] = {0.1,   -0.1, 1.01,  -1.01, 0.9,   -0.9,  1.49,
                            -1.59, 1,    -1,    2.5,   -5.0,  4.47,  -4.51,
                            5.001, 1.21, -2.42, 2.99,  5.055, 5.900, -0.5,
                            -0.9,  0.8,  2.3,   3.1,   4.2,   +1.21, -1.21};
  size_t n = sizeof(testcases_base) / sizeof(testcases_base[0]);

  for (size_t i = 0; i < n; i++) {
    for (size_t j = 0; j < n; j++) {
      long double result = s21_pow(testcases_base[i], testcases_exp[j]);
      double expected_result = pow(testcases_base[i], testcases_exp[j]);
      char result_str[LEN];
      char expected_str[LEN];
      sprintf(result_str, "%16.6Lf", result);
      sprintf(expected_str, "%16.6lf", expected_result);
      // ck_assert_ldouble_eq_tol(result, expected_result, 0.000001);
      ck_assert_pstr_eq(result_str, expected_str);
    }
  }
}
END_TEST

START_TEST(s21_pow_infnan) {
  long double result = s21_pow(NAN, 10);
  ck_assert_ldouble_nan(result);

  result = s21_pow(10, NAN);
  ck_assert_ldouble_nan(result);

  result = s21_pow(1., INFINITY);
  ck_assert_ldouble_eq(result, 1.);

  result = s21_pow(1., -INFINITY);
  ck_assert_ldouble_eq(result, 1.);

  result = s21_pow(INFINITY, 0);
  ck_assert_ldouble_eq(result, 1.);

  result = s21_pow(-INFINITY, 0);
  ck_assert_ldouble_eq(result, 1.);

  result = s21_pow(0, -5);
  ck_assert_ldouble_infinite(result);

  result = s21_pow(0, 5);
  ck_assert_ldouble_eq(result, 0.);

  result = s21_pow(-INFINITY, INFINITY);
  ck_assert_ldouble_infinite(result);

  result = s21_pow(INFINITY, -INFINITY);
  ck_assert_ldouble_eq(result, 0.);

  result = s21_pow(INFINITY, INFINITY);
  ck_assert_ldouble_infinite(result);

  result = s21_pow(-INFINITY, -INFINITY);
  ck_assert_ldouble_eq(result, 0.);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("wilmerno_functions_test");
  TCase *tc1_1 = tcase_create("s21_sin_test");
  TCase *tc1_2 = tcase_create("s21_cos_test");
  TCase *tc1_3 = tcase_create("s21_tan_test");
  TCase *tc1_4 = tcase_create("s21_acos_test");
  TCase *tc1_5 = tcase_create("s21_asin_test");
  TCase *tc1_6 = tcase_create("s21_atan_test");
  TCase *tc1_7 = tcase_create("s21_fmod_test");
  TCase *tc1_8 = tcase_create("s21_sqrt_test");
  Suite *s2 = suite_create("tabathae_functions_test");
  TCase *tc2_1 = tcase_create("s21_ceil_test");
  TCase *tc2_2 = tcase_create("s21_floor_test");
  TCase *tc2_3 = tcase_create("s21_exp_test");
  TCase *tc2_4 = tcase_create("s21_log_test");
  TCase *tc2_5 = tcase_create("s21_abs_test");
  TCase *tc2_6 = tcase_create("s21_fabs_test");
  TCase *tc2_7 = tcase_create("s21_pow_test");
  SRunner *sr = srunner_create(s1);
  int nf;

  /* User-specified pre-run code */

  tcase_set_timeout(tc2_7, 0);

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, s21_sin_circle);
  tcase_add_test(tc1_1, s21_sin_random);
  tcase_add_test(tc1_1, s21_sin_extreme);
  suite_add_tcase(s1, tc1_2);
  tcase_add_test(tc1_2, s21_cos_circle);
  tcase_add_test(tc1_2, s21_cos_random);
  tcase_add_test(tc1_2, s21_cos_extreme);
  suite_add_tcase(s1, tc1_3);
  tcase_add_test(tc1_3, s21_tan_circle);
  tcase_add_test(tc1_3, s21_tan_random);
  tcase_add_test(tc1_3, s21_tan_extreme);
  suite_add_tcase(s1, tc1_4);
  tcase_add_test(tc1_4, s21_acos_circle);
  tcase_add_test(tc1_4, s21_acos_random);
  tcase_add_test(tc1_4, s21_acos_extreme);
  suite_add_tcase(s1, tc1_5);
  tcase_add_test(tc1_5, s21_asin_circle);
  tcase_add_test(tc1_5, s21_asin_random);
  tcase_add_test(tc1_5, s21_asin_extreme);
  suite_add_tcase(s1, tc1_6);
  tcase_add_test(tc1_6, s21_atan_circle);
  tcase_add_test(tc1_6, s21_atan_random);
  tcase_add_test(tc1_6, s21_atan_extreme);
  suite_add_tcase(s1, tc1_7);
  tcase_add_test(tc1_7, s21_fmod_common);
  tcase_add_test(tc1_7, s21_fmod_random);
  tcase_add_test(tc1_7, s21_fmod_extreme);
  suite_add_tcase(s1, tc1_8);
  tcase_add_test(tc1_8, s21_sqrt_rational);
  tcase_add_test(tc1_8, s21_sqrt_irrational);
  tcase_add_test(tc1_8, s21_sqrt_random);
  tcase_add_test(tc1_8, s21_sqrt_extreme);
  suite_add_tcase(s2, tc2_1);
  tcase_add_test(tc2_1, s21_ceil_regular);
  tcase_add_test(tc2_1, s21__ceil_infnan);
  suite_add_tcase(s2, tc2_2);
  tcase_add_test(tc2_2, s21_floor_regular);
  tcase_add_test(tc2_2, s21_floor_infnan);
  suite_add_tcase(s2, tc2_3);
  tcase_add_test(tc2_3, s21_exp_regular);
  tcase_add_test(tc2_3, s21_exp_infnan);
  suite_add_tcase(s2, tc2_4);
  tcase_add_test(tc2_4, s21_log_regular);
  tcase_add_test(tc2_4, s21_log_infnan);
  suite_add_tcase(s2, tc2_5);
  tcase_add_test(tc2_5, s21_abs_regular);
  suite_add_tcase(s2, tc2_6);
  tcase_add_test(tc2_6, s21_fabs_regular);
  tcase_add_test(tc2_6, s21_fabs_infnan);
  suite_add_tcase(s2, tc2_7);
  tcase_add_test(tc2_7, s21_pow_regular);
  tcase_add_test(tc2_7, s21_pow_infnan);

  srunner_add_suite(sr, s2);

  srunner_run_all(sr, CK_VERBOSE);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
